### ISSUE TITLE
failed install

### ISSUE THREAD

**Issue by frocelu** [RobyFerro/go-web#1]
**Describe the bug**
Can't install this framework.

**To Reproduce**
go install failed with
`$GOPATH\pkg\mod\github.com\!roby!ferro\go-web-framework@v0.3.6-beta\http_server.go:150:12: undefined: syscall.Setuid
$GOPATH\pkg\mod\github.com\!roby!ferro\go-web-framework@v0.3.6-beta\http_server.go:163:12: undefined: syscall.Setgid`

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: windows 10 2004

**Comment by RobyFerro** [comment]
Please upgrade _go-web-framework_ dependency in go.mod to _"v0.3.7-beta"_ version.

**Comment by groovenectar** [comment]
The line in `go.mod` reads:

```
github.com/RobyFerro/go-web-framework v0.4.2-beta
```

But this error persists (Windows 10)... Could there have been a change in the Windows context since 0.3.7?
