### ISSUE TITLE
how can i help the project?

### ISSUE THREAD

**Issue by ggbr** [RobyFerro/go-web#4]
I'm a beginner in GO, but I've been working for years with PHP and Laravel, I'm loving the Go language but I really miss a framework like Laravel.

I would love to help the project by getting my hands dirty but I don't know where to start.

**Comment by RobyFerro** [comment]
Hi, I would appreciate your help! The goal of the project is to create a Go alternative to Laravel. 
If you want you can join the Slack workspace: https://join.slack.com/t/ikdevgroup/shared_invite/zt-ijbhpu9x-atwe9sC0Y0PZ_Gzq91pXyw

**Comment by reindert-vetter** [comment]
@ggbr @RobyFerro. The link is no longer active. Is this project still active? I am working on [confetti-framework.com](http://www.confetti-framework.com/). Maybe we can work together.

**Comment by RobyFerro** [comment]
> @ggbr @RobyFerro. The link is no longer active. Is this project still active? I am working on [confetti-framework.com](http://www.confetti-framework.com/). Maybe we can work together.

@reindert-vetter the project still active. You can join us at this [link](https://join.slack.com/t/go-webworkspace/shared_invite/zt-lu7zkiie-tHrMN30bPgga0al6limkow).
