### ISSUE TITLE
Failed Install

### ISSUE THREAD

**Issue by dbd5** [RobyFerro/go-web#6]
**Describe the bug**

It cannot be installed following the documentation provided at https://goweb.readthedocs.io/en/latest/installation.html;

**To Reproduce**
1. Setup environment as expected with &GOPATH environment variable
2. Following the docs run go get github.com/RobyFerro/go-web 
(downloads some packages)
3. Following the docs, cd $GOPATH/src/github.com/RobyFerro/go-web 
(cd: no such file or directory: ...)

**Expected behavior**

The install should copy the files to a valid path. 
The docs and command expects the path to be 
/Users/John/go/src/github.com/**RobyFerro**/go-web 

BUT it doesn't exist. The files are deployed to  
/Users/John/go/pkg/mod/github.com/**!roby!ferro**/go-web-framework@v0.4.2-beta
/Users/John/go/pkg/mod/github.com/**!roby!ferro**/go-web@v0.4.2-beta

**Desktop (please complete the following information):**
 - OS: macOS Catalina
 - Browser Chrome

**Additional context**
The funny looking path !roby!ferro has been reported in a previous error #1 seems, we can't get to build until we can cd. Is there a different documentation or am I doing something wrong?

**Comment by RobyFerro** [comment]
I've updated the documentation in order to simplify the installation process. Please follow [this](https://goweb.readthedocs.io/en/latest/installation.html) steps.
